/**
 * Arkista's Ring Sprite Definitions for Craven Caverns
 * Auto-generated by asset organization tool
 */

#ifndef ARKISTA_SPRITES_H
#define ARKISTA_SPRITES_H

// Player character sprites
#define SPRITE_PLAYER_0                0x4F
#define SPRITE_PLAYER_1                0x4D
#define SPRITE_PLAYER_2                0x4A
#define SPRITE_PLAYER_3                0x29
#define SPRITE_PLAYER_4                0x27
#define SPRITE_PLAYER_5                0x25
#define SPRITE_PLAYER_6                0x26
#define SPRITE_PLAYER_7                0x4C
#define SPRITE_PLAYER_8                0x4B
#define SPRITE_PLAYER_9                0x4E
#define SPRITE_PLAYER_10               0x28

// Enemy sprites
#define SPRITE_ENEMIES_0               0x3D
#define SPRITE_ENEMIES_1               0x39
#define SPRITE_ENEMIES_2               0x5F
#define SPRITE_ENEMIES_3               0x3F
#define SPRITE_ENEMIES_4               0x3E
#define SPRITE_ENEMIES_5               0x35
#define SPRITE_ENEMIES_6               0x5E
#define SPRITE_ENEMIES_7               0x33
#define SPRITE_ENEMIES_8               0x37
#define SPRITE_ENEMIES_9               0x36
#define SPRITE_ENEMIES_10              0x3B
#define SPRITE_ENEMIES_11              0x51
#define SPRITE_ENEMIES_12              0x30
#define SPRITE_ENEMIES_13              0x40
#define SPRITE_ENEMIES_14              0x58
#define SPRITE_ENEMIES_15              0x3A
#define SPRITE_ENEMIES_16              0x3C
#define SPRITE_ENEMIES_17              0x53
#define SPRITE_ENEMIES_18              0x50
#define SPRITE_ENEMIES_19              0x42
#define SPRITE_ENEMIES_20              0x59
#define SPRITE_ENEMIES_21              0x43
#define SPRITE_ENEMIES_22              0x45
#define SPRITE_ENEMIES_23              0x31
#define SPRITE_ENEMIES_24              0x38
#define SPRITE_ENEMIES_25              0x5A
#define SPRITE_ENEMIES_26              0x57
#define SPRITE_ENEMIES_27              0x55
#define SPRITE_ENEMIES_28              0x44
#define SPRITE_ENEMIES_29              0x54
#define SPRITE_ENEMIES_30              0x5B
#define SPRITE_ENEMIES_31              0x56
#define SPRITE_ENEMIES_32              0x32
#define SPRITE_ENEMIES_33              0x34
#define SPRITE_ENEMIES_34              0x52
#define SPRITE_ENEMIES_35              0x5D
#define SPRITE_ENEMIES_36              0x5C
#define SPRITE_ENEMIES_37              0x41

// Item sprites (weapons, armor, potions, etc.)
#define SPRITE_ITEMS_0                 0x7E
#define SPRITE_ITEMS_1                 0x6D
#define SPRITE_ITEMS_2                 0x7B
#define SPRITE_ITEMS_3                 0x70
#define SPRITE_ITEMS_4                 0x79
#define SPRITE_ITEMS_5                 0x7A
#define SPRITE_ITEMS_6                 0x76
#define SPRITE_ITEMS_7                 0x73
#define SPRITE_ITEMS_8                 0x7D
#define SPRITE_ITEMS_9                 0x62
#define SPRITE_ITEMS_10                0x6C
#define SPRITE_ITEMS_11                0x67
#define SPRITE_ITEMS_12                0x61
#define SPRITE_ITEMS_13                0x66
#define SPRITE_ITEMS_14                0x75
#define SPRITE_ITEMS_15                0x74
#define SPRITE_ITEMS_16                0x65
#define SPRITE_ITEMS_17                0x78
#define SPRITE_ITEMS_18                0x7F
#define SPRITE_ITEMS_19                0x6E
#define SPRITE_ITEMS_20                0x6A
#define SPRITE_ITEMS_21                0x69
#define SPRITE_ITEMS_22                0x6B
#define SPRITE_ITEMS_23                0x77
#define SPRITE_ITEMS_24                0x60
#define SPRITE_ITEMS_25                0x64
#define SPRITE_ITEMS_26                0x68
#define SPRITE_ITEMS_27                0x63
#define SPRITE_ITEMS_28                0x71
#define SPRITE_ITEMS_29                0x7C
#define SPRITE_ITEMS_30                0x6F
#define SPRITE_ITEMS_31                0x72

// Environment tiles (walls, floors, doors, stairs)
#define SPRITE_ENVIRONMENT_0           0xB0
#define SPRITE_ENVIRONMENT_1           0xB1
#define SPRITE_ENVIRONMENT_2           0xA3
#define SPRITE_ENVIRONMENT_3           0xB4
#define SPRITE_ENVIRONMENT_4           0xB7
#define SPRITE_ENVIRONMENT_5           0xA4
#define SPRITE_ENVIRONMENT_6           0xB8
#define SPRITE_ENVIRONMENT_7           0xA7
#define SPRITE_ENVIRONMENT_8           0xB5
#define SPRITE_ENVIRONMENT_9           0xBB
#define SPRITE_ENVIRONMENT_10          0xB9
#define SPRITE_ENVIRONMENT_11          0xAF
#define SPRITE_ENVIRONMENT_12          0xA1
#define SPRITE_ENVIRONMENT_13          0xAB
#define SPRITE_ENVIRONMENT_14          0xBC
#define SPRITE_ENVIRONMENT_15          0xB6
#define SPRITE_ENVIRONMENT_16          0xAD
#define SPRITE_ENVIRONMENT_17          0xAE
#define SPRITE_ENVIRONMENT_18          0xBE
#define SPRITE_ENVIRONMENT_19          0xB2
#define SPRITE_ENVIRONMENT_20          0xB3
#define SPRITE_ENVIRONMENT_21          0xA5
#define SPRITE_ENVIRONMENT_22          0xBF
#define SPRITE_ENVIRONMENT_23          0xAC
#define SPRITE_ENVIRONMENT_24          0xA2
#define SPRITE_ENVIRONMENT_25          0xA8
#define SPRITE_ENVIRONMENT_26          0xA0
#define SPRITE_ENVIRONMENT_27          0xAA
#define SPRITE_ENVIRONMENT_28          0xBD
#define SPRITE_ENVIRONMENT_29          0xBA
#define SPRITE_ENVIRONMENT_30          0xA6
#define SPRITE_ENVIRONMENT_31          0xA9

// UI elements (fonts, indicators, etc.)
#define SPRITE_UI_0                    0xD4
#define SPRITE_UI_1                    0xD2
#define SPRITE_UI_2                    0xDA
#define SPRITE_UI_3                    0xD0
#define SPRITE_UI_4                    0xCC
#define SPRITE_UI_5                    0xC7
#define SPRITE_UI_6                    0xDC
#define SPRITE_UI_7                    0xC3
#define SPRITE_UI_8                    0xDF
#define SPRITE_UI_9                    0xCD
#define SPRITE_UI_10                   0xC9
#define SPRITE_UI_11                   0xCF
#define SPRITE_UI_12                   0xD6
#define SPRITE_UI_13                   0xC2
#define SPRITE_UI_14                   0xC4
#define SPRITE_UI_15                   0xD7
#define SPRITE_UI_16                   0xC1
#define SPRITE_UI_17                   0xD9
#define SPRITE_UI_18                   0xC8
#define SPRITE_UI_19                   0xD3
#define SPRITE_UI_20                   0xDE
#define SPRITE_UI_21                   0xCA
#define SPRITE_UI_22                   0xC6
#define SPRITE_UI_23                   0xCB
#define SPRITE_UI_24                   0xDB
#define SPRITE_UI_25                   0xC5
#define SPRITE_UI_26                   0xD1
#define SPRITE_UI_27                   0xD5
#define SPRITE_UI_28                   0xDD
#define SPRITE_UI_29                   0xCE
#define SPRITE_UI_30                   0xC0
#define SPRITE_UI_31                   0xD8

// Roguelike game elements
#define SPRITE_WALL_0                  0xA3
#define SPRITE_WALL_1                  0xA1
#define SPRITE_WALL_2                  0xA2
#define SPRITE_WALL_3                  0xA0
#define SPRITE_FLOOR_0                 0xA4
#define SPRITE_FLOOR_1                 0xA7
#define SPRITE_FLOOR_2                 0xA5
#define SPRITE_FLOOR_3                 0xA6
#define SPRITE_CHEST_0                 0x61
#define SPRITE_CHEST_1                 0x60
#define SPRITE_STAIRS_0                0xAB
#define SPRITE_STAIRS_1                0xAA
#define SPRITE_DOOR_0                  0xA8
#define SPRITE_DOOR_1                  0xA9

#endif // ARKISTA_SPRITES_H
